
package View;

import Controller.CorreosCtrl;
import Controller.EnterosCtrl;
import Controller.RealesCtrl;
import javax.swing.JOptionPane;

/**
 *
 * @author pillo
 */
public class Menu_Principal extends javax.swing.JFrame {

    /*Inicio de Objetos*/
    EnterosCtrl entctrl = new EnterosCtrl();
    RealesCtrl relctrl = new RealesCtrl();
    CorreosCtrl corctrl = new CorreosCtrl();    
    /*Fin de Objetos*/
    
    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_fallo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_cadena = new javax.swing.JTextField();
        labelR = new javax.swing.JLabel();
        btn_verificar = new javax.swing.JButton();
        btn_reiniciar = new javax.swing.JButton();
        CmbTipos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Verificador de Cadenas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        txt_fallo.setEnabled(false);
        jPanel1.add(txt_fallo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, -1));

        jLabel2.setText("Cadena a verificar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setText("Caracter provocador de fallo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        jPanel1.add(txt_cadena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, -1));

        labelR.setText("Resultado:");
        jPanel1.add(labelR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        btn_verificar.setText("Verificar");
        btn_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verificarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 110, -1));

        btn_reiniciar.setText("Reiniciar");
        btn_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 110, -1));

        CmbTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NumEntero", "NumReal", "Correo" }));
        jPanel1.add(CmbTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verificarActionPerformed
        limpiartxterror();
        estadoVerificar(false);
        if (CmbTipos.getSelectedItem() == "NumEntero") {
            if (entctrl.Automata(txt_cadena.getText()) == true) {
                labelR.setText("Resultado: Es un entero");
            }else{
                estadoVerificar(true);
                txt_fallo.setText(entctrl.obtenerFallo());
                labelR.setText("Error lexico");
            }
        }else if(CmbTipos.getSelectedItem() == "NumReal"){
            if (relctrl.Automata(txt_cadena.getText()) == true) {
                labelR.setText("Resultado: Es un Real");
            }else{
                estadoVerificar(true);
                txt_fallo.setText(relctrl.obtenerFallo());
                labelR.setText("Error lexico");
            }
        }else if(CmbTipos.getSelectedItem() == "Correo"){
            if (corctrl.Automata(txt_cadena.getText()) == true) {
                labelR.setText("Resultado: Es un correo");
            }else{
                estadoVerificar(true);
                txt_fallo.setText(corctrl.obtenerFallo());
                labelR.setText("Error lexico");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ningun tipo de verificacion seleccionada");
        }
    }//GEN-LAST:event_btn_verificarActionPerformed

    private void btn_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reiniciarActionPerformed
        estadoReiniciar(true);
    }//GEN-LAST:event_btn_reiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbTipos;
    private javax.swing.JButton btn_reiniciar;
    private javax.swing.JButton btn_verificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelR;
    private javax.swing.JTextField txt_cadena;
    private javax.swing.JTextField txt_fallo;
    // End of variables declaration//GEN-END:variables

private void estadoVerificar(boolean state){
    btn_verificar.enable(state);
}

private void estadoReiniciar(boolean state){
    btn_reiniciar.enable(state);
    txt_cadena.setText("");
    txt_fallo.setText("");
    estadoVerificar(true);
}

private void limpiartxterror(){
    txt_fallo.setText("");
}

}
